### PR TITLE
Release v2.26.0+rev1

### PR DESCRIPTION
**Pull request by floion**

### CODE REVIEW

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by nazrhom** [comment]
@resin-ci retest

**Comment by mikesimos** [comment]
@resin-jenkins test

**Comment by mikesimos** [comment]
@resin-jenkins test

**Comment by mikesimos** [comment]
@resin-jenkins test this please

**Comment by mikesimos** [comment]
@resin-jenkins test this please

**Comment by floion** [comment]
@resin-jenkins test this please

**Comment by mikesimos** [comment]
@resin-jenkins retest this please

**Comment by mikesimos** [comment]
@resin-jenkins test this please

**Pull request merged**
